### ISSUE TITLE
Seems to infinite-loop

### ISSUE THREAD

**Issue by JangoSteve** [augustl/js-inflate#3]
I may be doing something incredibly wrong, but I figured I'd post this in case you've seen it before. I cannot seem to get this library to work with any of my zip files. Whenever I call `JSInflate.inflate` on a zipped entry (from the js-unzip library), my processor gets pegged at 100% and it seems to be causing an infinite loop in this: `while((i = zip_inflate_internal(buff, 0, buff.length)) > 0)`

Here is my full code:

```js
$('input:file').live('change', function() {
  var file = this.files[0],
  r = new FileReader();

  r.onload = function(e) {
    var unzipper = new JSUnzip(r.result);

    if (unzipper.isZipFile()) {
      unzipper.readEntries();
      for (var i = 0, var len = unzipper.entries.length; i < len; i++) {
        var entry = unzipper.entries[i];
        getEntry(entry);
      }
    }

  r.readAsBinaryString(file);
});

getEntry = function(entry) {
  var uncompressed;
  if (entry.fileName.match(/some_file_name/)) {
    if (entry.compressionMethod == 0) {
      // Uncompressed
      uncompressed = entry.data
    } else if (entry.compressionMethod == 8) {
      // Deflated
      console.log('inflating...');
      uncompressed = JSInflate.inflate(entry.data);
      console.log(uncompressed);
    }
};
```
As you can see, I'm only trying to uncompress one file within the Zip (and it's a small 1.5KB text file). It get's to the `inflating...` line, but that's when the CPU gets pegged in Chrome (in FF, it'll say the script has stopped responding). Putting some debug code in js-inflate, it looks like the aforementioned line is infinite-looping.

Also, I tried the dankogai/js-deflate library, and it does the exact same thing.

**Comment by augustl** [comment]
Hey :) Just deprecated this project. There are now well maintained alternative modules that didn't exist when I orginally created this project. I've linked to a few of them in the README :)
