### ISSUE TITLE
JSInflate.inflate not working

### ISSUE THREAD

**Issue by Harsha12345678** [augustl/js-inflate#5]
For a zip with xml file alone I got the entry properly but if I give that as input for inflate uncompressed = JSInflate.inflate(entry.data); (where entry = unzipper.entries[0]). I am getting uncompressed data as empty.

i.e. inflate is resulting empty data.

Please review and suggest.

**Comment by augustl** [comment]
Hey :) Just deprecated this project. There are now well maintained alternative modules that didn't exist when I orginally created this project. I've linked to a few of them in the README :)
